### ISSUE TITLE
Search for a particular person is giving me a 500

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#899] opened 2020-06-17 19:32 UTC
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
`https://demo.acvts.nist.gov/acvp/v1/persons?fullName[0]=contains:lawlor`. **GET**

**Expected behaviour**
This seems to be specific to this particular query, but when run, I'm getting:
```json
[
    {
        "acvVersion": "1.0"
    },
    {
        "error": "Internal service error. Contact service provider."
    }
]
```

Filtering/querying for other names seem to work correctly.

**Comment by celic** [comment] 2020-06-24 17:31
Did we determine this is a duplicate of #895 ?

**Comment by AlexThurston** [comment] 2020-06-24 17:32
Yeah.  They were related.  In both cases, the person is was trying to returned had incomplete data.

**Comment by celic** [comment] 2020-06-24 17:33
Thanks. We will track through #895.

**Closed by celic** 2020-06-24 17:33 UTC
