### ISSUE TITLE
AES-CFB1 MMT tests seem to fail incorrectly

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#183] opened 2017-07-25 17:56 UTC
I'm debugging the AES-CFB1 tests since that was the last AES that we had yet to complete
and when I compare my ACVP results to those from openssl command line vector testing
I get the same result, however ACVP server is returning them as failed.
I only comparison tested these 4, the first one text case passed.

  "algorithm" : "AES-CFB1",
  "testGroups" : [ {
    "direction" : "encrypt",
    "testType" : "AFT",
    "keyLen" : 128,
    "tests" : [ {
      "tcId" : 1,
      "iv" : "9187E2CCF15B2AF2CF957CAB09F9F8A4",
      "key" : "37ECA9F6B8F59FE3389EEA2A83A07E71",
      "pt" : "0"
    }, {
      "tcId" : 2,
      "iv" : "6EBC174643BF38B30A01C57FDF28EF70",
      "key" : "C9483B93CED7C8E10D8F1F368787BC02",
      "pt" : "00"
    }, {
        "tcId" : 9,
      "iv" : "97673CBB9F0F960AA38CA1A00157B3C3",
      "key" : "7943917368715376AC29EC6E04AF7DE5",
      "pt" : "001010011"
    }, {
      "tcId" : 10,
      "iv" : "DC003497D79D92E1CB780DDCE437EEAD",
      "key" : "5D48014888D0D2817EB6DE6C9A531350",
      "pt" : "1010101101"
    } ]

Client response:

        "vsId": 175,
        "algorithm": "AES-CFB1",
        "testResults": [
            {
                "tcId": 1,
                "ct": "0"
            },
            {
                "tcId": 2,
                "ct": "10"
            },
                 "tcId": 9,
                "ct": "001010010"
            },
            {
                "tcId": 10,
                "ct": "0110000101"
            },
Server results:
  "results" : {
    "vsId" : 175,
    "disposition" : "fail",
    "tests" : [ {
      "tcId" : 1,
      "result" : "passed"
    }, {
      "tcId" : 2,
      "result" : "fail",
      "reason" : "Cipher Text does not match"
    }, {
      "tcId" : 9,
      "result" : "fail",
      "reason" : "Cipher Text does not match"
    }, {
      "tcId" : 10,
      "result" : "fail",
      "reason" : "Cipher Text does not match"
    }, {

openssl results:

[ENCRYPT]

COUNT = 0
KEY = 37ECA9F6B8F59FE3389EEA2A83A07E71
IV = 9187E2CCF15B2AF2CF957CAB09F9F8A4
PLAINTEXT = 0
CIPHERTEXT = 0

COUNT = 1
KEY = C9483B93CED7C8E10D8F1F368787BC02
IV = 6EBC174643BF38B30A01C57FDF28EF70
PLAINTEXT = 00
CIPHERTEXT = 10

COUNT = 2
KEY = 7943917368715376AC29EC6E04AF7DE5
IV = 97673CBB9F0F960AA38CA1A00157B3C3
PLAINTEXT = 001010011
CIPHERTEXT = 001010010

COUNT = 3
KEY = 5D48014888D0D2817EB6DE6C9A531350
IV = DC003497D79D92E1CB780DDCE437EEAD
PLAINTEXT = 1010101101
CIPHERTEXT = 0110000101

**Comment by atvassilev** [comment] 2017-07-25 18:24
Interesting. I have been working on a research project with some of my colleagues on the next gen testing for ACVP. In the process, we encountered and reported a similar problem with OpenSSL in a paper that is accepted for presentation at a conference this fall. 

Our testing revealed that the OpenSSL and LibreSSL command line tool’s AES-128-CFB1, AES- 192-CFB1, and AES-256-CFB1 block ciphers do not produce the ciphertexts and plaintexts found in the CAVP test suites.

As a concrete example, consider the CFB1MMT128.rsp  test suite, and in particular, the following test data:

[ENCRYPT]
KEY = 1e3b6e224a79a5e40e4a1c084bdad9cb
IV = 4c55a0bae99ab9f4e9cdcb0238b8c525
PLAINTEXT = 111
CIPHERTEXT = 101
For the given key, IV, and plaintext, the OpenSSL and LibreSSL command line tool’s AES-128-CFB1 block cipher produces the following ciphertext: 44.

**Comment by bfussell** [comment] 2017-07-25 19:30
"produces the following ciphertext: 44." Was something cut off here or am I missing something ?

Here is our output from running that key, iv and plaintext with our version of openssl :

COUNT = 0
KEY = 1e3b6e224a79a5e40e4a1c084bdad9cb
IV = 4c55a0bae99ab9f4e9cdcb0238b8c525
PLAINTEXT = 111
CIPHERTEXT = 101

and with ACVP:

        "vsId": 178,
        "algorithm": "AES-CFB1",
        "testResults": [
            {
                "tcId": 61,
                "ct": "101"
            }
        ]

**Comment by atvassilev** [comment] 2017-07-25 19:42
Hmm, no cutoff, if I recall correctly the output was 44 (don't have the setup to run the test on my machine). You seem to be able to reproduce the correct value so that makes it strange that the server fails.

**Comment by atvassilev** [comment] 2017-07-25 20:59
Upon further checking, I take back the assertion that the problem was with OpenSSL. It looks like the test harness that was used in this experiment had an error causing the input '111' to be misinterpreted as hex  0x11 which is 17 in decimal. The issue here is different and we need to look at the server side.

**Comment by Kritner** [comment] 2017-07-26 11:10
@bfussell I was going to start taking a look at this - can you confirm whether or not you've gotten through the MCT tests for CFB1 successfully?  That'll give me a good starting point to narrow it down around the IV manipulation between blocks, assuming you have successfully gotten through the MCT tests.

**Comment by bfussell** [comment] 2017-07-26 12:00
@Kritner Yes, the MCT for CFB1 tests are working.  I have made code changes that handle the MMT and MCT test cases that have not been committed to libacvp master yet.  Is that something you need to help debugging ?

**Comment by atvassilev** [comment] 2017-07-26 12:58
Just to be clear, the same situation applies to LibreSSL - the issue was with the test harness, not the library.

**Comment by Kritner** [comment] 2017-07-26 13:00
@bfussell  no rush on that - I've at least confirmed that our crypto portion for CFB1 is producing your expected results, it's *seemingly* something around either the writing or reading of the bit oriented bitstrings in our json files.  Haven't quite narrowed down the location yet - but that helps that MCT is working, thanks!

**Comment by Kritner** [comment] 2017-07-26 18:55
I narrowed down the issue to bit oriented bit strings being printed in the reverse order in the JSON files for AES-CFB1, this only presented itself as an issue for MMT due to all other tests being a single bit input/output.

I have a fix in locally and have a question into the team on next steps for getting out to at least demo.

**Comment by Kritner** [comment] 2017-07-28 13:46
@bfussell a fix has been pushed the the demo environment and is ready for testing.

Let me know if you need anything else!

**Comment by bfussell** [comment] 2017-07-28 13:51
Tested and is now working

**Closed** 2017-07-28 13:51 UTC
Labels: bug

**Comment by Kritner** [comment] 2017-07-28 13:53
Awesome!  And wow that was fast! :)
