### ISSUE TITLE
TDES CTR: undefined  testType entries in test vectors

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#233] opened 2018-03-02 12:48 UTC
The TDES CTR JSON test vector contains the following testType entries:

  }, {
    "direction" : "encrypt",
    "testType" : "InversePermutation",

or 

  }, {
    "direction" : "encrypt",
    "testType" : "Permutation",

Others are also found.

These test types are not defined.

**Comment by celic** [comment] 2018-03-07 18:25
Duplicate of #248 which has been resolved.

**Closed by celic** 2018-03-07 18:25 UTC
Labels: bug
