### ISSUE TITLE
RSA Revision Tag Syntax Issue?

### ISSUE THREAD

**Issue by mtdownz** [usnistgov/ACVP#990] opened 2020-09-08 20:14 UTC
**environment**
Demo Server

**testSessionId**
The test session ID

**vsId**
N/A - Non assigned

**Algorithm registration**
```
[
  { "acvVersion": "1.0" },
  {
    "isSample": true,
    "algorithms": [
      {
        "algorithm": "RSA",
        "revision": "FIPS186-4",
        "mode": "sigVer",
        "prereqVals": [
          {
            "algorithm": "SHA",
            "valValue": "same"
          },
          {
            "algorithm": "DRBG",
            "valValue": "same"
          }
        ],
        "pubExpMode": "random",
        "capabilities": [
          {
            "sigType": "ansx9.31",
            "properties": [
              {
                "modulo": 2048,
                "hashPair": [
                  { "hashAlg": "SHA-1" },
                  { "hashAlg": "SHA2-256" },
                  { "hashAlg": "SHA2-384" },
                  { "hashAlg": "SHA2-512" }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
]
```

**Endpoint in which the error is experienced**
***ACVP [INFO][log_network_status:1467]--> POST Registration...
	Status: 400
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions
	Resp: Recieved

**Expected behavior**
Following your guidance per the RSA ACVP documentation section 5, we changed our RSA vector request information from using “1.0” to either “FIPS186-4” or “FIPS186-2” (legacy sigver) but receive the following error from the Demo server (also attached):

***ACVP [ERR][log_network_status:1491]--> 400 error received from server. Message:
***ACVP [ERR][log_network_status:1492]--> 
```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Unable to map RSA-keyGen-FIPS186-4 - index 0 to an internal algorithm id."
    ]
  }
]
```

Note: When we use a value of “1.0” in the Revision tag with the attached JSON there is no issues and we receive the vectors. Is the Demo server currently supporting these updated “Revision” values documented in Section 5
https://usnistgov.github.io/ACVP/draft-celi-acvp-rsa.html

These tags are important for accessing FIPS 186-2 Legacy SigVer. 

**Additional context**
The intent is to access Legacy SigVer using this method. Is there another method available?

**Comment by Kritner** [comment] 2020-09-09 15:15
This seems to be a specification error, probably just a typo from when we were in the process of moving over to the new metanorma documentation.

"186-5" is the only valid value aside from "1.0"  to access legacy sig ver you'd use "RSA" / "LegacySigVer" / "1.0"

I'll get the specification updated to reflect the above.

**Comment by Kritner** [comment] 2020-09-09 15:34
After talking about it internally, it seems there was an intention of getting the algorithms renamed to fit the current specification.  That may be happening, but in the interim the above from https://github.com/usnistgov/ACVP/issues/990#issuecomment-689630157 can be used.

**Comment by mtdownz** [comment] 2020-09-09 15:48
Thank you.

**Comment by Kritner** [comment] 2020-09-09 16:30
I mentioned it in https://github.com/cisco/libacvp/issues/485, but I'll reiterate here, I plan on getting the algorithms renamed within our ACVP implementation to support the naming of the algorithms from the document linked here https://usnistgov.github.io/ACVP/draft-celi-acvp-rsa.html

This will be a breaking change to clients when it rolls out, and it will likely be a (at least few day) gap in time between when it rolls out between demo and prod.

I'll update this ticket with the few algorithm identifier changes once i have a chance to switch over to that task and identify them.

**Comment by Kritner** [comment] 2020-09-09 17:22
Here are the expected changes to the current vs new algorithm identifiers.  Not sure at the moment when this change will be going out to demo and then prod, but will keep the issue updated.

| Old Identifier | New Identifier |
| --- | --- |
| RSA / KeyGen / 1.0 | RSA / KeyGen / FIPS186-4 |
| RSA / SigGen / 1.0 | RSA / SigGen / FIPS186-4 |
| RSA / SigVer / 1.0 | RSA / SigVer / FIPS186-4 |
| RSA / LegacySigVer / 1.0 | RSA / SigVer / FIPS186-2 |

**Comment by Kritner** [comment] 2020-09-09 17:26
@smuellerDD tagging to make sure you're aware of an upcoming client breaking change due to several RSA algo/mode/revision name changes.

**Comment by abkarcher** [comment] 2020-09-09 17:29
So just to make sure I understand completely, 1.0 Will no longer be an acceptable "revision" value for the aforementioned alg/mode combos, and the spec doesn't yet reflect this (for KeyGen and SigGen)?

Thanks,
Andrew

**Comment by Kritner** [comment] 2020-09-09 17:42
> Just to make sure I understand completely, 1.0 Will no longer be an acceptable "revision" value for the aforementioned alg/mode combos, and the spec doesn't yet reflect this (for KeyGen and SigGen)?

Correct, the additional changes two changes are in #991, though all of the renames are not yet present in either demo or prod.

the "Old Identifier" in the table from https://github.com/usnistgov/ACVP/issues/990#issuecomment-689706002 *should* be reflective of what is currently on both demo and prod, and the "New Identifier" is what demo and prod will be updated to.

I believe this encompasses all the changes, but if you see anything I've missed please let me know.

The demo change will be going out first (I'd imagine within the next few days), then prod some time after.  I know client breaking changes are no fun... hopefully everyone can understand the reasoning behind making this change at least.

**Comment by abkarcher** [comment] 2020-09-09 18:05
Hello,

Would it be possible to have "FIPS186-4" be added to the demo environment prior to 1.0 being removed so I can sufficiently test and release a client update before this change is made and our users aren't able to perform RSA testing? I currently get an error performing a registration with FIPS186-4. 

Thanks for your time,
Andrew

**Comment by celic** [comment] 2020-09-09 18:13
Sorry, at the moment we cannot do that. If you need testing for users, you can always pull vectors ahead of time with the sample flag. Or re-use an old completed vector set. As mentioned, the FIPS186-4 revision is mislabeled as 1.0. This issue is tracking when the revision will be updated to FIPS186-4. This is just the demo environment, so unique testing is just a luxury. We will make the fix on Prod at a later time. 

Due to how some other systems are set up behind the scenes, we cannot have multiple names point to the same item without performing additional unnecessary work.

**Comment by tobyp** [comment] 2020-09-11 11:14
> Here are the expected changes to the current vs new algorithm identifiers. Not sure at the moment when this change will be going out to demo and then prod, but will keep the issue updated.
> 
> Old Identifier	New Identifier
> RSA / KeyGen / 1.0	RSA / KeyGen / FIPS186-4
> RSA / SigGen / 1.0	RSA / SigGen / FIPS186-4
> RSA / SigVer / 1.0	RSA / SigVer / FIPS186-4
> RSA / LegacySigVer / 1.0	RSA / SigVer / FIPS186-2

None of these work at the moment (`Unable to map RSA-_${MODE}_-FIPS186-4 - index ${INDEX} to an internal algorithm id.`), see also #995 .

> "186-5" is the only valid value aside from "1.0" to access legacy sig ver you'd use algo "RSA", mode "LegacySigVer", revision "1.0"

I also trued just "186-4" without the FIPS to no avail.

**Comment by Kritner** [comment] 2020-09-11 12:19
Yeah sorry it looks like there is an issue with the deployment to demo, I'll update this ticket once it's patched

**Comment by Kritner** [comment] 2020-09-11 14:43
regarding https://github.com/usnistgov/ACVP/issues/990#issuecomment-691033681 and #995, the fix is now on demo.  Let me know if there are any further issues.

**Comment by Kritner** [comment] 2020-09-11 17:55
I meant to keep this issue open until it's on prod

**Comment by smuellerDD** [comment] 2020-09-11 19:32
keyGen and sigGen seem to work, but:

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Error on RSA-sigVer-FIPS186-4 - index 2: Unable to map algo (RSA), mode (sigVer), and revision (FIPS186-4) to AlgoMode"
    ]
  }
]
```

The registration contains:

```
        "revision":"FIPS186-4",
        "algorithm":"RSA",
        "mode":"sigVer",
        "pubExpMode":"random",
```

**Comment by Kritner** [comment] 2020-09-11 19:51
@smuellerDD that should now be fixed on demo. Sorry about that!

**Comment by smuellerDD** [comment] 2020-09-11 19:53
Confirmed, working.

**Comment by mtdownz** [comment] 2020-09-13 00:44
Attempts at FIPS 186-2 Legacy SigVer seems to be throwing a General Exception:

Status: 200
Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/115454/vectorSets/326947
Resp:

[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "General exception. Contact service provider."
  }
]
The following is the JSON request for reference:
[{"acvVersion":"1.0"},{"isSample":true,"algorithms":[{"algorithm":"RSA","revision":"FIPS186-2","mode":"sigVer","prereqVals":[{"algorithm":"SHA","valValue":"same"},{"algorithm":"DRBG","valValue":"same"}],"pubExpMode":"fixed","fixedPubExp":"010001","capabilities":[{"sigType":"pkcs1v1.5","properties":[{"modulo":1024,"hashPair":[{"hashAlg":"SHA-1"}]},{"modulo":1536,"hashPair":[{"hashAlg":"SHA-1"}]}]}]}]}]

Same failure for Random Exponents as well

**Comment by Kritner** [comment] 2020-09-13 14:45
@mtdownz this is actually unrelated to the name change and some internal checks being done on modulo that aren't working at they should.  I opened the new issue to track the problem: https://github.com/usnistgov/ACVP-Server/issues/3

**Comment by mtdownz** [comment] 2020-09-23 02:31
Regarding the name change...was this deployed to both the Demo and Production or just Demo. I am now successful getting RSA Legacy SigVer using the FIPS186-2 tag on the Demo but throw the same error noted when I opened this issue on the Production. Should I be still using the mode value LegacySigVer on the Production instead? Thanks!!

**Comment by Kritner** [comment] 2020-09-23 02:37
This change is still currently on demo, this release to prod is being held up longer than usual due to some other changes unrelated to this issue that require coordination with other teams.  I will update this issue when I have more information about the production release date.

Thank you to everyone for your patience.

**Comment by Kritner** [comment] 2020-09-30 21:12
this change is now on production https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.12

Clients must now use the updated labels in all environments

**Closed by Kritner** 2020-09-30 21:12 UTC
Labels: Client Breaking Change, Server enhancement, Spec error
