### ISSUE TITLE
Hash DRBG: server failure

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#315] opened 2018-04-08 21:23 UTC
When requesting a Hash DRBG test vector, I get:

```
{
  "vsId" : 391,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 391"
} ]
```

**Comment by celic** [comment] 2018-04-09 18:31
Can you post the algorithm specific part of the registration? There are a lot of options for Hash DRBG so I am having trouble reproducing the error.

**Comment by smuellerDD** [comment] 2018-04-09 19:12
Am Montag, 9. April 2018, 20:31:44 CEST schrieb Chris Celi:

Hi Chris,

> Can you post the algorithm specific part of the registration? There are a
> lot of options for Hash DRBG so I am having trouble reproducing the error.

```
{
          "algorithm":"hashDRBG",
          "prereqVals":[
            {
              "algorithm":"SHA",
              "valValue":"same"
            }
          ],
          "predResistanceEnabled":[
            false,
            true
          ],
          "reseedImplemented":false,
          "capabilities":[
            {
              "mode":"SHA-1",
              "derFuncEnabled":false,
              "entropyInputLen":[
                160
              ],
              "nonceLen":[
                160
              ],
              "persoStringLen":[
                160
              ],
              "additionalInputLen":[
                160
              ],
              "returnedBitsLen":640
            },
            {
              "mode":"SHA2-224",
              "derFuncEnabled":false,
              "entropyInputLen":[
                256
              ],
              "nonceLen":[
                128
              ],
              "persoStringLen":[
                256
              ],
              "additionalInputLen":[
                256
              ],
              "returnedBitsLen":1024
            },
            {
              "mode":"SHA2-256",
              "derFuncEnabled":false,
              "entropyInputLen":[
                256
              ],
              "nonceLen":[
                128
              ],
              "persoStringLen":[
                256
              ],
              "additionalInputLen":[
                256
              ],
              "returnedBitsLen":1024
            },
            {
              "mode":"SHA2-384",
              "derFuncEnabled":false,
              "entropyInputLen":[
                256
              ],
              "nonceLen":[
                128
              ],
              "persoStringLen":[
                256
              ],
              "additionalInputLen":[
                256
              ],
              "returnedBitsLen":1024
            },
            {
              "mode":"SHA2-512",
              "derFuncEnabled":false,
              "entropyInputLen":[
                256
              ],
              "nonceLen":[
                128
              ],
              "persoStringLen":[
                256
              ],
              "additionalInputLen":[
                256
              ],
              "returnedBitsLen":2048
            }
          ]
        },
```

Ciao
Stephan

**Comment by celic** [comment] 2018-04-09 20:24
Ok. So for this, it looks like the registration is incorrect in some places. To start, the `returnedBitsLen` must be a multiple of the digest size of the hash function. As well when `derFuncEnabled` is `false`, the `entropyInputLen`, and `nonceLen` must match the digest size of the hash function. 

This would be the same for #316. I mentioned elsewhere that more informative errors are in the pipeline and this is an example where they would be beneficial.

**Comment by smuellerDD** [comment] 2018-04-09 20:58
Am Montag, 9. April 2018, 22:24:50 CEST schrieb Chris Celi:

Hi Chris,

> Ok. So for this, it looks like the registration is incorrect in some places.
> To start, the `returnedBitsLen` must be a multiple of the digest size of
> the hash function.

This is a surprise: why is that? I took the values from the HMAC/Hash DRBG 
test vectors generated by the old CAVS tool.

> As well when `derFuncEnabled` is `false`, the
> `entropyInputLen`, and `nonceLen` must match the digest size of the hash
> function.

Again, this is a surprise. If there is no DF, there should be no nonce to 
begin with (but that was reported in a different issue already).

So, for SHA-512, the entropyInputLen must be 512 bits? I think this does not 
seem right.
> 
> This would be the same for #316. I mentioned elsewhere that more informative
> errors are in the pipeline and this is an example where they would be
> beneficial.


Ciao
Stephan

**Comment by celic** [comment] 2018-04-11 21:02
@smuellerDD go ahead and try this and #316 again. We just deployed a fix. The nonce lower bound should be equal to the security strength of the hash function used. The returned bit lengths must be a multiple of the digest size of the hash function. This is in line with CAVS that asked for a number of output blocks (and the multiplication I mentioned above was performed behind the scenes).

**Comment by smuellerDD** [comment] 2018-04-12 07:56
Am Mittwoch, 11. April 2018, 23:02:42 CEST schrieb Chris Celi:

Hi Chris,

> @smuellerDD go ahead and try this and #316 again. We just deployed a fix.
> The nonce lower bound should be equal to the security strength of the hash
> function used.

Ok, with that I can download test vectors. Yet, I believe that this is not 
consistent with SP800-90A section 8.6.7: the nonce is half of the security 
strength, *if* a nonce is needed at all. You do not need a nonce for CTR DRBG 
without DF.

> The returned bit lengths must be a multiple of the digest
> size of the hash function. This is in line with CAVS that asked for a
> number of output blocks (and the multiplication I mentioned above was
> performed behind the scenes).

Btw: is the issue regarding the zero persolen and addtl len fixed?

Ciao
Stephan

**Comment by atvassilev** [comment] 2018-04-12 12:37
Well, it is also not consistent with the DRBG spec on GitHub. Indeed the nonce should be at least half the security strength.

**Comment by celic** [comment] 2018-04-12 16:10
Sorry if there was confusion, That is already the case for CTR DRBG. No nonce is needed for CTR DRBG without a derivation function... No server change is required here. I was talking about the nonce length for the Hash and HMAC DRBGs specifically (which do not have an option for a derivation function.)

I'm looking into the persoLen and addtlLen issue to see if it has been resolved.

**Comment by smuellerDD** [comment] 2018-04-19 06:55
Just to add a detail: for one IUT that validated HMAC-DRBG in the past with the old CAVS tool, we used the following options:
SHA-1:  entropy 128 bits, nonce 64 bits
SHA-224: entropy 192, nonce 96
SHA-256/384/512: entropy 256, nonce 128

**Comment by celic** [comment] 2018-05-16 20:56
This has been fixed and is going through testing before being pushed to the external environment. I will close the ticket when I get confirmation it has been deployed.

**Comment by celic** [comment] 2018-05-21 14:47
This fix has been deployed. Please test again and let me know if there are any issues.

**Comment by smuellerDD** [comment] 2018-05-22 10:06
Neither for HMAC-DRBG nor for Hash-DRBG nor for CTR-DRBG I get vectors. I always get the following errors

```
[ {
  "acvVersion" : "0.4"
}, {
  "vsId" : 1212,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 1212"
} ]
```

vsID 1212 == Hash DRBG request
vsID 1211 == HMAC DRBG request
vsID 1309 == CTR DRBG request

**Comment by celic** [comment] 2018-05-22 14:55
Please see pg 38 and 49 from [SP800-90A](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-90Ar1.pdf) for the allowed fields.

**Closed** 2018-05-22 18:37 UTC
Labels: Numerical code bug, Web server bug

**Comment by celic** [comment] 2018-05-22 19:47
SHA2-224. 1024 bits is not divisible by 224 bits. A service that tells you that something is wrong with out telling you _what_ is wrong, is not a very useful service. :)

**Comment by smuellerDD** [comment] 2018-05-22 19:54
Am Dienstag, 22. Mai 2018, 21:47:47 CEST schrieb Chris Celi:

Hi Chris,

> SHA2-224. 1024 bits is not divisible by 224 bits. A service that tells you
> that something is wrong with out telling you _what_ is wrong, is not a very
> useful service. :)

After hitting the send button, I realized that :-)

Then I changed it and voila, it works :-D

Ciao
Stephan
