### ISSUE TITLE
GET requests with URL encoded apostrophe (%27) return 500 internal service error (Demo and prod)

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#921] opened 2020-07-16 21:20 UTC
Hello! Found an issue while querying the server for vendors/modules  for matching. The following query:
`acvp/v1/vendors?name[0]=eq:Cisco%27s%20Systems%2C%20Inc.&website[0]=eq:www.cisco.com`
Results in: 
```
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Internal service error. Contact service provider."
  }
```
While `acvp/v1/vendors?name[0]=eq:Cisco%20Systems%2C%20Inc.&website[0]=eq:www.cisco.com` works fine. It seems the %27 apostrophe URL code is causing this.

Also was the case for module querying and seemed to persist regardless of property queried. Happens on both Demo and prod.

Thanks,
Andrew

**Comment by celic** [comment] 2020-07-17 14:02
This is a duplicate of #915 perhaps?

**Comment by abkarcher** [comment] 2020-07-17 14:07
Hello,

 #915 refers to the server sending URLs to the client inside json data that are not URL encoded. 
This is a situation where the server seems to experience an internal error when a client uses a properly encoded URL request. They are covering similar topics but at least in my opinion are not related. The URLs I was using to experience this error were generated by our client to query for a module and were not sent by the server.

Thanks,
Andrew

**Comment by Kritner** [comment] 2020-07-20 10:01
Thanks @abkarcher I'll put in a fix for this

**Comment by Kritner** [comment] 2020-07-21 14:07
The fix for this is now on demo and prod, let me know if you encounter any issues

**Closed by Kritner** 2020-07-21 14:07 UTC
