### ISSUE TITLE
Failure of Post /testSessions for RSASigGen/RSASigVer since the latest maintenence

### ISSUE THREAD

**Issue by RoyHSYoo** [usnistgov/ACVP#995] opened 2020-09-11 02:05 UTC
**environment**
The environment the issue was experienced (Demo or Prod) Demo

**testSessionId**
The test session ID

**vsId**
The vectorSet ID displaying the issue

**Algorithm registration**
The pertinent algorithm registration pieces (algorithm tested, capabilities, etc) in json format
[
	{"acvVersion":"1.0"},
	{
		"isSample":true,
		"algorithms": [
			{
				"algorithm": "RSA",
				"mode": "sigGen",
				"revision": "1.0",
				"pubExpMode" : "fixed",
				"fixedPubExp" : "010001",
				"capabilities" : 
				[
					{	"sigType" : "pkcs1v1.5",
						"properties" :
						[
							{ "modulo" : 2048,
								"hashPair" : [
								{
									"hashAlg" : "SHA2-256"
								}
								]
							}
						]
					},
					{
						"sigType" : "pss",
						"properties" :
						[
							{ "modulo" : 2048,
								"hashPair" : [
								{
									"hashAlg" : "SHA2-256",
									"saltLen" : 32
								}
								]
							}
						]
					}
				]
			}
		]
	}
]

**Endpoint in which the error is experienced** https://demo.acvts.nist.gov/acvp/v1/testSessions POST
https://[acvpUrl]/acvp/[endpoint] GET

**Expected behavior**
I had been able to get vectorSetUrls for RSASigGen/SigVer but is not able to currently.

**Additional context**

When I tried to post capabilities above, I could see only the error messages below:
'Error on RSA-sigVer-1.0 - index 0: Unable to find External representation of algorithm.'
'Error on RSA-sigGen-1.0 - index 0: Unable to find External representation of algorithm.'

**Comment by RoyHSYoo** [comment] 2020-09-11 02:29
I have just checked the latest document. It seems the expected value of "revision" has been changed from "1.0" to "FIPS186-4" so I tried to get with the changed capabilities but failed with the different error messages:
'Unable to map RSA-sigVer-FIPS186-4 - index 0 to an internal algorithm id.'
'Unable to map RSA-sigGen-FIPS186-4 - index 0 to an internal algorithm id.'

**Comment by Kritner** [comment] 2020-09-11 08:32
Thanks, I have an idea of what's wrong.

It's still pretty early here, but once folks start waking up I'll have
someone with access to the environment take care of the issue.

**Comment by tobyp** [comment] 2020-09-11 10:38
I've also encountered this error since tonight.

**Error:** Validation error(s) on JSON payload.

I tried three different revisions (for three modes in one test session) and received three different errors:

**context:** Unable to map RSA-keyGen-FIPS186-4 - index 13 to an internal algorithm id.
**context:** Error on RSA-sigGen-1.0 - index 14: Unable to find External representation of algorithm.

**Comment by Kritner** [comment] 2020-09-11 12:20
I'm closing this issue for now, please see #990 for updates (when the issue is fixed).

**Closed by Kritner** 2020-09-11 12:20 UTC
