### ISSUE TITLE
TOTP seed cannot be verified

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#422] opened 2018-07-24 00:52 UTC
We are not able to authenticate to the server... we just keep getting 401 with "The supplied one time password could not be verified". Maybe one of the recent updates changed a something related to TOTP? Any ideas? Maybe I missed an email about needing a new seed?

Thanks!

**Comment by hbooth** [comment] 2018-07-24 15:41
No changes were made in the code or the seeds, AFAIK. I just restarted the JBoss service. Please try that and let me know if it works now.
I can see the failures in our log files, but I don't have quite enough information to determine exactly where the problem is. Since this has come up a few times, I added some additional information for our logs so we can try to track down the issue better. This additional logging information is not yet deployed but we are planning on a deployment soon and this change would go out with that.

**Comment by smuellerDD** [comment] 2018-07-24 15:57
Am Dienstag, 24. Juli 2018, 17:41:12 CEST schrieb Harold Booth:

Hi Harold,

> No changes were made in the code or the seeds, AFAIK. I just restarted the
> JBoss service. Please try that and let me know if it works now. I can see
> the failures in our log files, but I don't have quite enough information to
> determine exactly where the problem is. Since this has come up a few times,
> I added some additional information for our logs so we can try to track
> down the issue better. This additional logging information is not yet
> deployed but we are planning on a deployment soon and this change would go
> out with that.

Confirmed - I can log in and get test vectors.

Ciao
Stephan

**Comment by bfussell** [comment] 2018-07-24 17:50
Maybe it’s just the Cisco seed, I still can’t login.

Barry

**Comment by celic** [comment] 2018-07-24 19:59
Back before IETF I had some similar troubles with the Cisco client setting up TOTP. It would only work on a specific version of Ubuntu (16.04) and OpenSSL (1.0.2g). That and because I was on a VM, I had to make sure there was no clock skew. 

I ended up trying to track down the specific lines causing the problem with a known good password and implementation trying to see where the difference came from with the Cisco client. It ended up around https://github.com/cisco/libacvp/blob/18eed1dcd7da5bbb4bdf11f0deb7875e172253da/app/app_main.c#L5052 through L5059. I didn't try to fix it before trying Ubuntu 16.04 which worked immediately.

**Comment by bfussell** [comment] 2018-07-24 21:43
I don’t see any logic issue with that piece of code. I’ve stepped thru
it and it’s doing what I expect.  Could you please re-issue us a new
seed and make sure it’s assigned to our cert ?

Thanks,

Barry

**Comment by jarnold01** [comment] 2018-07-25 15:02
I have corrected the issue by replacing the seed value entry in the database with the correct one and Barry verified it working. I have updated the necessary components on my end to ensure the proper seed value will persist on any future environment updates.

**Closed** 2018-07-25 15:03 UTC
