### ISSUE TITLE
Demo Server retry: 30 issue

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP#1047] opened 2020-10-27 18:56 UTC
Issue: Demo Server Retry Issue

Reproducibility: 50%

Repro case
1.	POST a new Test Session with 2 to 20 algorithm capabilities objects.
2.	GET each vector set in the test session (either one at a time or sending multiple requests simultaneously).

Expected result
Either the vector set downloads or the requestor receives an accurate retry message.

Actual result
About 50% of the time, I get a retry: 30 message. From those, waiting 30 seconds and retrying results in another retry: 30 message. Repeating sometimes takes up to 30 minutes or more to download the vector sets in question.

Impact:
We have ramped up our ACVP migration effort. We have 6 modules containing from 2 to 25 vector sets that require certification over 34 OEs, so we will be making several of these requests per day.

Here is a log of two attempts. One thing that seems odd to me is the timestamp in the returned HTTP headers only appears in the first two requests (which represents one attempt to download two vector sets). I made several attempts over 5 minutes and always received the last two request/response shown.

Is there something I'm doing that would cause this behavior? 

```
endpoint:  "https://demo.acvts.nist.gov/acvp/v1/testSessions/122906/vectorSets/365457"
"GET"  path /acvp/v1/testSessions/122906/vectorSets/365457
endpoint:  "https://demo.acvts.nist.gov/acvp/v1/testSessions/122906/vectorSets/365458"
"GET"  path /acvp/v1/testSessions/122906/vectorSets/365458
"returned headers\nHTTP/1.1 200 OK\r\nContent-Type: application/json; charset=utf-8\r\nServer: Microsoft-IIS/8.5\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains; preload\r\nDate: Tue, 27 Oct 2020 18:27:57 GMT\r\nContent-Length: 67\r\n\r\n"
reply "[
  {
    "acvVersion": "1.0"
  },
  {
    "retry": 30
  }
]"
"returned headers\nHTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\nContent-Type: application/json; charset=utf-8\r\nServer: Microsoft-IIS/8.5\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains; preload\r\nDate: Tue, 27 Oct 2020 18:27:57 GMT\r\n\r\n"
reply "[
  {
    "acvVersion": "1.0"
  },
  {
    "retry": 30
  }
]"
"GET"  path /acvp/v1/testSessions/122906/vectorSets/365457
endpoint:  "https://demo.acvts.nist.gov/acvp/v1/testSessions/122906/vectorSets/365458"
"GET"  path /acvp/v1/testSessions/122906/vectorSets/365458
"returned headers\nHTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\nContent-Type: application/json; charset=utf-8\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains; preload\r\n\r\n"
reply "[
  {
    "acvVersion": "1.0"
  },
  {
    "retry": 30
  }
]"
"returned headers\nHTTP/1.1 200 OK\r\nContent-Type: application/json; charset=utf-8\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains; preload\r\nContent-Length: 67\r\n\r\n"
reply "[
  {
    "acvVersion": "1.0"
  },
  {
    "retry": 30
  }
]"
```

Thanks,
Jeff

**Comment by celic** [comment] 2020-10-27 20:25
For some context on the back-end, when we receive many algorithm registrations, we allocate a process to generate each individual vector set. We have a limited amount of these we can have running at once, for ALL users. Depending on the algorithms, these can be very computationally expensive. What _may_ end up happening is if another user is submitting requests for several large algorithms (like RSA or KAS) it may lead to longer than expected wait times for a vector set prompt. I can't say for certain this is happening here. I can look into this a bit and see what I can find out.

**Comment by celic** [comment] 2020-10-28 00:14
I do not have experience with that from a client perspective. We have had
issues today with our internal clustering service that distributes the
generation tasks, I later found out. It is set up to never go fully offline
so nothing is lost, but we did lose some throughput during the afternoon.

**Comment by celic** [comment] 2020-10-28 15:41
I think we've identified the issue on our end. Your system should be fine. Definitely a server issue causing poor performance, but not crashing. The issue is not related to your requests, you just happened to make the requests during the affected period.

**Comment by jbarnesweb** [comment] 2020-11-06 17:22
I still see a lot of retry: 30. Same response headers.

One thing I noticed is that if I close my application and run it again, the vector set download will succeed. Why no timestamp in the subsequent responses after the initial retry: 30?

**Comment by celic** [comment] 2020-11-06 17:32
Interesting, the headers are the exact same between each retry response? I do not see that behavior on Demo. Each request I make that response with a retry has different headers in the response. 

```
Content-Type: application/json; charset=utf-8
Date: Fri, 06 Nov 2020 17:29:11 GMT
Server: Microsoft-IIS/8.5
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Transfer-Encoding: chunked
```

and then

```
Content-Type: application/json; charset=utf-8
Date: Fri, 06 Nov 2020 17:29:49 GMT
Server: Microsoft-IIS/8.5
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Transfer-Encoding: chunked
```

**Comment by celic** [comment] 2020-11-06 17:43
I see what you mean in your initial issue, the timestamp is not present in the headers in the later responses. Is there a way for you to check if anything in your application or network is caching the response here?

**Comment by celic** [comment] 2020-11-19 21:20
Any update on this before we close it out? This is not something we are able to reproduce on our end.

**Closed** 2021-08-09 10:59 UTC
