### ISSUE TITLE
RSADP 56Br2 Implementation: Public Exponent

### ISSUE THREAD

**Issue by Ani11226** [usnistgov/ACVP#1467] opened 2023-09-01 11:05 UTC
Hello, 
We wanted to request guidance pertaining to the following issue related to the RSADP algorithm: The current RSADP implementation on the ACVTS DEMO/PROD servers per NIST SP 800-56Br2 does not seem to permit specifying a static/fixed public key exponent value. When such a value is specified, the DEMO server seems to be ignoring it and providing request vectors with a random exponent (e) value. This is resulting in the issue that the implementation in its current form is not testable for one of our clients (as their implementation expects a fixed exponent). If the CAVP could please advise next steps/potential workarounds here, we would greatly appreciate it!

**Comment by jbrock24** [comment] 2023-09-01 16:31
I'll take a look at this!

**Comment by Ani11226** [comment] 2023-09-05 10:47
Thank you!

**Comment by livebe01** [comment] 2023-09-07 15:59
Hi @Ani11226, can you help us better understand the issue you're experiencing? Looking at SP 800-56Br2, sections 7.1.2.1, 7.1.2.2, and 7.1.2.3, we wouldn't expect the IUT to be using e in the computation of RSADP.

**Comment by livebe01** [comment] 2023-09-21 12:59
Hi @Ani11226, I wanted to confirm whether this is still an open issue?  Or can it be closed?

**Comment by Ani11226** [comment] 2023-09-22 06:00
Hey, this is still an open issue. I'll get back on this with a better understanding of the issue within next 2 to 3 days.

Thank you for your patience!

**Comment by klali** [comment] 2023-10-11 10:50
Hi,

Jumping in here a bit since we're having the same issue.

Typically the public exponent is needed in the RSA blinding operation.
It's also needed if one wants to verify the private operation just performed by running the opposing public operation.

**Comment by mtdownz** [comment] 2023-10-13 22:18
Would love to get some feedback on this issue otherwise I guess we would need to 'Vendor Affirm' the RSADP for fixed exponents?

**Comment by celic** [comment] 2023-10-16 18:20
How does the implementation use the public exponent for decryption? Is it just part of the key format needed to run the algorithm? Is there any verification of the key used? I guess I don't understand why a blank `e` value couldn't be provided because the public exponent does not factor into the result.

**Comment by klali** [comment] 2023-10-17 07:35
The typical rsa blinding operation is computed as `x * r ^ e % n` where `x` is the input and `r`is random, this is the main reason we want to be able to specify a fixed public exponent.

**Comment by celic** [comment] 2023-10-17 17:38
Ah OK, similar to a scheme defined in SP 800-106 (recently withdrawn). Is the blinding operation used in the result at all? How would this verify with the server if we compute the expected result based on the definition in SP 800-56Br2?

**Comment by klali** [comment] 2023-10-18 08:51
No, not quite. This is done to randomize the message for the operations with the private keys, after the private operations are done the result is unblinded as `c * r ^ -1 % n`, this yields the expected output for verification. This is desirable to have as part of all rsa operations since it protects the private values by always masking the input with randomness.

**Comment by celic** [comment] 2023-10-18 17:41
Interesting. Thanks for the insight. I think we will update this, and include a registration parameter `usesBlinding` to track if we need to provide the `e` value. It is up to the implementation to obtain `r`.

**Comment by Ani11226** [comment] 2023-10-18 17:54
> Hi @Ani11226, I wanted to confirm whether this is still an open issue? Or can it be closed?

Hi @livebe01,
I would like to close this ticket as we have come to a conclusion on our side regarding the issue based on the comments here. I would really like to thank CAVP team and you for providing your valuable opinion/suggestion on this Issue.

**Comment by celic** [comment] 2023-10-18 17:58
Sorry, we're going to keep this open to track the progress of the resolution on the server-side.

**Comment by klali** [comment] 2023-10-18 18:25
Thanks @celic will this change enable us to use a fixed exponent as well?

**Comment by celic** [comment] 2023-10-18 18:28
Yes, sorry I misunderstood the original issue. I thought we weren't including the `e` value. We are, it is just always random. Yes, we will fix this to allow `fixedPublicExponent`.

**Comment by jbrock24** [comment] 2023-10-18 19:20
Hi all, I've made the changes to the spec to support this. It will be out with our next release. We'll reply here and close the thread once it's done. Thanks for the discussion!

**Comment by livebe01** [comment] 2023-11-21 17:01
The fix for this is on Demo in release [v1.1.0.32](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.32).

**Comment by jbrock24** [comment] 2023-11-27 14:27
Thank you, mistake on my part, I'll fix this.

**Comment by jbrock24** [comment] 2023-12-05 19:29
@jeanpaulgalea  I wanted to let you know I am currently reversing this, we will make it a single string and not a list. Apologies for all the confusion, but this will go out with the next hotfix. I will reply here when that is done.

**Comment by jeanpaulgalea** [comment] 2023-12-06 08:30
@jbrock24 no problem, that sounds good. Thanks for keeping us in the loop.

**Comment by livebe01** [comment] 2023-12-12 13:41
Fyi, we just deployed a hotfix to Demo. `pubExpMode` now expects a string (vs an array).

**Comment by jeanpaulgalea** [comment] 2023-12-13 10:46
Thanks @livebe01!

I can confirm that Demo now expects `"pubExpMode": "fixed"` and that it successfully generates vectors and accepts responses.

**Comment by livebe01** [comment] 2023-12-15 15:03
The fix for this is on Prod in release [v1.1.0.32](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.32).

**Closed by livebe01** 2023-12-15 15:03 UTC
