### ISSUE TITLE
SHA3/SHAKE spec mirror sha1/2 domain changes?

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#625] opened 2019-04-09 17:20 UTC
Hello,

I was wondering if at some point the SHA3/SHAKE specification will use a domain value for the messageLength (replacing inEmpty and inBit) and eliminating outBit? This would bring it inline with how the SHA1/2 spec is currently designed, and I like this approach.

Thanks!
Phil

**Comment by celic** [comment] 2019-04-09 18:12
I also like the approach. The problem lies within the SHAKE MCTs. They are not well designed for a domain value at the moment. They require the domain to consist of a single minimum and maximum pair as the MCT algorithm has no concept of selecting a valid length from a varied domain. 

I am also in favor of redesigning the SHAKE MCTs so that they can properly accept a domain. After that is completed, changing SHA3/SHAKE over to mirror SHA1/2 would be trivial.

**Comment by celic** [comment] 2020-11-05 16:10
Stay tuned for SHA3 revision 2.0 which allows a registration similar to SHA2. Documentation in progress.

**Comment by celic** [comment] 2020-11-16 18:17
Duplicate of #1003

**Closed by celic** 2020-11-16 18:17 UTC
