### ISSUE TITLE
Can HMAC msgLen be changed

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#943] opened 2020-08-07 01:29 UTC
**environment**
Demo

**testSessionId**
/acvp/v1/testSessions/100152

**vsId**
/acvp/v1/testSessions/100152/vectorSets/290774

It seems the msgLen will always be '128' in the test vectors. We cannot set the msgLen in the registration of HMAC and the selected SHA algorithms have no impact to the msgLen either.

Can I ask whether it's something you expected and msgLen of HMAC is not expected to be changed?

**Comment by celic** [comment] 2020-08-10 15:21
Duplicate of #944, going with that one.

**Closed by celic** 2020-08-10 15:21 UTC
