### ISSUE TITLE
CTR DRBG: "failed to generate tests for: 3595"

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#285] opened 2018-03-23 15:48 UTC
Requesting a CTR DRBG test vector with the JSON request outlined below fails with the following response:
```
[ {
  "acvVersion" : "0.4"
}, {
  "vsId" : 3595,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 3595"
} ]
```

Request:
``` 
       {
          "algorithm":"ctrDRBG",
          "prereqVals":[
            {
              "algorithm":"AES",
              "valValue":"same"
            }
          ],
          "predResistanceEnabled":[
            false,
            true
          ],
          "reseedImplemented":true,
          "capabilities":[
            {
              "mode":"AES-256",
              "derFuncEnabled":false,
              "entropyInputLen":[
                256
              ],
              "nonceLen":[
                128
              ],
              "persoStringLen":[
                256
              ],
              "additionalInputLen":[
                256
              ],
              "returnedBitsLen":512
            }
          ]
        },

```

**Comment by Kritner** [comment] 2018-03-26 14:24
@smuellerDD `"derFunctionEnabled": false` and `AES-256` require an `entropyInputLen` equal to the `seedLength` of 384 (OutputLength [128] + KeyLength [256])

**Comment by smuellerDD** [comment] 2018-03-26 15:17
Ok, but noncelen cannot be set to 0 to increase the entropy string as outlined in #239

**Comment by Kritner** [comment] 2018-03-28 20:31
@atvassilev I'm not sure if this is a bug at all, it's working as intended that it's rejecting this registration.  As @smuellerDD pointed out there is another bug related to DRBG that is actually an issue on the driver side.

But as far as I can tell, this issue can be closed, unless I'm misunderstanding @smuellerDD 's response

**Comment by atvassilev** [comment] 2018-03-28 20:33
@Kritner I see and agree, just wanted to make sure I am not closing it prematurely.

**Closed by atvassilev** 2018-03-28 20:33 UTC
Labels: Web server bug
