### ISSUE TITLE
Unable to receive TestVector of RSA sigVer

### ISSUE THREAD

**Issue by RoyHSYoo** [usnistgov/ACVP#1002] opened 2020-09-14 01:09 UTC
Hi,

Since the last server maintenance has been completed, I could receive TestVector of RSA sigGen again.
However, for RSA sigVer, it looks still have some issue. I tried to get TestVector using retrieved sub url but it returned "Retry" continuously.

Could you check the url below? I tried about waiting for 900 seconds (30 seconds * 30 times) but could not.
/acvp/v1/testSessions/115564/vectorSets/327594

**Comment by smuellerDD** [comment] 2020-09-14 06:32
Am Montag, 14. September 2020, 03:09:57 CEST schrieb RoyHSYoo:

Hi RoyHSYoo,

> Hi,
> 
> Since the last server maintenance has been completed, I could receive
> TestVector of RSA sigGen again. However, for RSA sigVer, it looks still
> have some issue. I tried to get TestVector using retrieved sub url but it
> returned "Retry" continuously.
> 
> Could you check the url below? I tried about waiting for 900 seconds (30
> seconds * 30 times) but could not.
> /acvp/v1/testSessions/115564/vectorSets/327594

It was successful for me - note there are cases where the server is under load 
and the generation of the RSA vectors takes some time.

Reconnect now and try to fetch that vsID and see whether it was generated.

Ciao
Stephan

**Comment by RoyHSYoo** [comment] 2020-09-14 06:59
Hi @smuellerDD,

I'm still getting the only "retry" for that url  :(
[{'acvVersion': '1.0'}, {'retry': 30}]

**Comment by smuellerDD** [comment] 2020-09-14 08:02
Am Montag, 14. September 2020, 08:59:24 CEST schrieb RoyHSYoo:

Hi RoyHSYoo,

> Hi @smuellerDD,
> 
> I'm still getting the only "retry" for that url  :(
> [{'acvVersion': '1.0'}, {'retry': 30}]

A colleage triggered an RSA sigVer test vector generation also waits for 2 
days.

Ciao
Stephan

**Comment by Kritner** [comment] 2020-09-14 09:34
There is currently an issue in our internal processing for RSA sigVer FIPS186-4.  We'll get out a patch once it's not quite so early here.  Closing this as a duplicate of https://github.com/usnistgov/ACVP-Server/issues/4.  I'll update that issue when the change is out.

Additionally from my [comment](https://github.com/usnistgov/ACVP-Server/issues/4#issuecomment-691938566):

> Once the change does go out you can either re-submit the test session or if you want us to save that particular one let me know, it's currently in a bad state and wouldn't automatically "be fixed" by the new deployment when it goes out.

**Closed by Kritner** 2020-09-14 09:34 UTC
