### ISSUE TITLE
ACVP search: /persons does not seem to apply search

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#648] opened 2019-05-22 06:06 UTC
The client performs the following request:

```
GET /acvp/v1/persons?fullName[0]=contains:Stephan%20M%C3%BCller?offset=100&limit=100 HTTP/1.1
```

The response contains:
```
}, {
  "totalCount" : 14150,
  "incomplete" : true,
  "links" : {
    "first" : "/acvp/v1/persons?offset=0&limit=100",
    "next" : "/acvp/v1/persons?offset=100&limit=100",
    "prev" : null,
    "last" : "/acvp/v1/persons?offset=14100&limit=100"
  },
```

It seems to imply that for the persons, a search is not performed. 

For example, for /vendors the search works:

```
GET /acvp/v1/vendors?name[0]=contains:atsec%20corp.&limit=100 HTTP/1.1
```

```
}, {
  "totalCount" : 6,
  "incomplete" : false,
  "links" : {
    "first" : "/acvp/v1/vendors?offset=0&limit=100&name[0]=contains:atsec+corp.",
    "next" : null,
    "prev" : null,
    "last" : "/acvp/v1/vendors?offset=0&limit=100&name[0]=contains:atsec+corp."
  },
```

And the search just returned a few entries.

**Comment by smuellerDD** [comment] 2019-05-22 06:29
I also seem to crash something in the server. Due to a glitch on my client, I invoked

```
GET /acvp/v1/persons?fullName[0]=contains:Stephan%20M%C3%BCller?offset=100&limit=100 HTTP/1.1
```

for the 2nd paging request (i.e. disregarding the provided URL in the "next" pointer.

The server returned an internal server error.

**Comment by smuellerDD** [comment] 2019-05-22 06:59
Note, I only checked /vendor and /persons so far. Thus, if you check this issue, could you please verify the other endpoints as well?

**Comment by hbooth** [comment] 2019-05-22 15:22
As you have guessed, if the paging response does not include your query parameters on output then the parameters were rejected/ignored. I could instead return an error response instead, but I wasn't sure what would be preferable.

I was able to quickly reproduce (and fix) the issue with persons (it was an encoding issue that is easily resolved by a configuration change that didn't make it out).

I am unable to reproduce the internal server error. What is the exact URL you are attempting to use?

I tried:
```
GET /acvp/v1/persons?fullName[0]=contains:Stephan%20M%C3%BCller?offset=100&limit=100
```
and it did not produce the internal server error

**Comment by hbooth** [comment] 2019-05-22 15:23
Note: The fix for the encoding issue is not out quite yet. I will update this issue when it is out.

**Comment by smuellerDD** [comment] 2019-05-22 15:41
Am Mittwoch, 22. Mai 2019, 17:22:51 CEST schrieb Harold Booth:

Hi Harold,

> As you have guessed, if the paging response does not include your query
> parameters on output then the parameters were rejected/ignored. I could
> instead return an error response instead, but I wasn't sure what would be
> preferable.

I think it is better to return the full output as you did. This way, even when 
the server has an issue or the query is messed up by the client, data is 
communicated.

In my client, I initially create the first URL with the search terms. But then 
I use the "next" pointer in the paging answer for any subsequent requests.
> 
> I was able to quickly reproduce (and fix) the issue with persons (it was an
> encoding issue that is easily resolved by a configuration change that
> didn't make it out).
> 
> I am unable to reproduce the internal server error. What is the exact URL
> you are attempting to use?
> 
> I tried:
> ```
> GET
> /acvp/v1/persons?fullName[0]=contains:Stephan%20M%C3%BCller?offset=100&limi
> t=100 ```
> and it did not produce the internal server error

Well, I used the URL for one ongoing HTTP session twice in a row - it was 
always reproducible for more than 5 times in a row. However, the bug only 
appeared after I had some previous HTTP sessions where I hammered the server 
with this GET request as I initially failed to see my bug.

So, have one HTTP session where you invoke the URL many times (say 100 times). 
Then terminate the HTTP session and start that test again. Eventually, the 
issue should appear.

Ciao
Stephan

**Comment by hbooth** [comment] 2019-05-22 16:30
I should have done this to begin with, but I checked our logs and was able to see what triggered the errors you saw and put in some additional checking to prevent the error response in the future.

A fix should be pushed out later today.

**Comment by hbooth** [comment] 2019-05-22 21:35
a fix for both of the items identified in this issue have been pushed out.

**Closed by hbooth** 2019-05-22 21:35 UTC
