### ISSUE TITLE
DRBG: range data type

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#217] opened 2018-02-26 21:46 UTC
The DRBG specification defines the range type in table 3 for various keywords. However, the examples in appendix A seem to define an array. Which data type is the correct one?

**Comment by Kritner** [comment] 2018-03-01 14:38
As mentioned in #222, `Domain` should be the norm.  an `int[]` can work passed into a `Domain` (by design). 

Updated in PR #217 to change `range` to `Domain` for consistency.  I'll close this ticket once the PR is approved, unless there was something else.

**Comment by celic** [comment] 2018-03-01 15:24
This is closed with #228

**Closed by celic** 2018-03-01 15:24 UTC
