### ISSUE TITLE
Failure in generating test vector

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#732] opened 2019-10-29 23:55 UTC
The server replies:

```
[ {
  "acvVersion" : "1.0"
}, {
  "vsId" : 67957,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 67957"
} ]
```

**Comment by Kritner** [comment] 2019-11-04 17:37
Going to close this for now as it appears to be a duplicate of #719

**Closed by Kritner** 2019-11-04 17:37 UTC
