### ISSUE TITLE
SHA-1 is missing from FIPS 186-5 ECDSA signature verification

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP#1464] opened 2023-08-27 01:59 UTC
SHA-1 is missing from FIPS 186-5 ECDSA signature verification, see https://github.com/usnistgov/ACVP/blob/master/src/ecdsa/sections/05-ecdsa-sigver-capabilities.adoc.
Note that FIPS 186-5 RSA signature verification *does* have it: https://github.com/usnistgov/ACVP/blob/master/src/rsa/sections/05-sigver-capabilities.adoc

**Comment by jbrock24** [comment] 2023-08-28 23:12
Hi @jvdsn , that's by design. 186-5 ECDSA SigVer doesn't support the EoL SHA-1, we won't be implementing support for that Hash with ECDSA. 186-4 does support it, so that would need to be used instead. Thanks for the question!

**Comment by jvdsn** [comment] 2023-08-28 23:22
@jbrock24 I'm sorry, but I don't understand this decision. There is nothing specifically in FIPS 186-5 that disallows the usage of SHA-1 for signature verification (or signature generation for that matter). And even if there was, why wouldn't it apply to RSA? Moreover, this change isn't included in the transitions in IG D.K, so I'm not even sure if we are allowed to claim FIPS 186-4 SHA-1 ECDSA signature verification after February 2024.

Vendors will always validate the most approved algorithms possible. This change (and others related to FIPS 186-5) means we now have to request the following FIPS 186 vector sets:

- RSA key pair generation (FIPS 186-5)
- RSA signature generation (FIPS 186-5)
- RSA signature verification (FIPS 186-5)
- RSA signature verification (ANS X9.31 padding and/or 1024-bit modulus) (FIPS 186-4)
- ECDSA key pair generation (P curves) (FIPS 186-5)
- ECDSA key pair verification (P curves) (FIPS 186-5)
- ECDSA key pair verification (P-192 and K/B curves) (FIPS 186-4)
- ECDSA signature generation (P curves) (FIPS 186-5)
- ECDSA signature generation (K/B curves) (FIPS 186-4)
- ECDSA signature verification (P curves) (FIPS 186-5)
- ECDSA signature verification (P-192 and K/B curves, and/or SHA-1) (FIPS 186-4)

As you can see, the number of vector sets almost doubled, and I don't really see the benefit. These are all FIPS approved/allowed algorithms. Is this really the intent of the CAVP?

**Comment by celic** [comment] 2023-08-29 18:02
Yeah that part appears to be a slip up. Coincidentally I wrote that, though I probably wrote that back in 2019 when a draft of FIPS 186-5 was available.

**Comment by jvdsn** [comment] 2024-01-21 04:31
@celic as of right now, the server still accepts SHA-1 for FIPS 186-5 RSA SigVer. Can we expect this to remain?

**Comment by celic** [comment] 2024-01-24 15:52
I'll slip this in to our upcoming release. It should not be there technically.

**Comment by livebe01** [comment] 2024-02-01 15:39
The fix for this is on Demo in release [v1.1.0.33](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.33)

**Comment by livebe01** [comment] 2024-02-09 15:51
The fix for this is on Prod in release [v1.1.0.33](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.33)

**Closed by livebe01** 2024-02-09 15:51 UTC
