### ISSUE TITLE
Hours long wait for vectors

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1123] opened 2021-02-05 05:51 UTC
Hi

We have been experiencing hours long waits for vectors from the ACVP demo system during the Australia / Melbourne working day.

So nominally 21:30 UTC to 06:00 UTC.

The registration completes but we just enter continual retries.

We abandoned the attached EDDSA request after almost two hours and just to check we started an a request for AES vectors which at the time of writing this ticket is at ~40 minutes of retries.

I have included the capabilities request, the registration response in the zip files.

[AES.zip](https://github.com/usnistgov/ACVP/files/5930393/AES.zip)

[EDDSA.zip](https://github.com/usnistgov/ACVP/files/5930387/EDDSA.zip)

Let me know if I you need any more information.

MW

**Comment by smuellerDD** [comment] 2021-02-05 06:32
Am Donnerstag, dem 04.02.2021 um 21:51 -0800 schrieb MW:

Considering the queue process on the server, it is possible that there is a
high volume of requests.

Note, you do not need to constantly poll the server after the 30 seconds. You
can stop polling for an extensive amount of time and resume the polling at a
later time. Our client commonly only registers the cipher definitions and then
shuts down. After some hours, I come back to request the data and usually it
takes only a minute or two to get all vectors.

Ciao
Stephan

**Comment by mwcw** [comment] 2021-02-05 06:34
@smuellerDD 

We back off as the server directs.

MW

**Comment by dghgit** [comment] 2021-02-07 03:26
It might be worth increasing the callback to 60 seconds, or more, if pinging the server is becoming an issue.

It's now Sunday afternoon here in Oz, usually the very quiet time. I do not even seem to be able to get back vectors for secure hash, which are probably, server-wise, one of the simplest things to generate. Vector set URLs come back straight away, but after that it's like my request has disappeared into a black hole. Something really doesn't seem right.

I while update this comment if the request actually returns.

**Comment by Kritner** [comment] 2021-02-07 13:52
Requests are processed in the order they're received, if there is a large queue of requests on demo, which there often is, it can take some time to fulfill the backlog.  

We're always looking for ways to improve things, but some of the algorithms just take time to process.

**Comment by dghgit** [comment] 2021-02-07 22:08
A happy coincidence then. 

An observation. 

In the "good old days" we used to download the CAVP test vectors from the NIST website and then get everything working from those. This mostly worked as what was produced by the testing tool was close enough to what they made available and the gaps in the ones they published was quite small so prior to trying to test with a lab people would get things mostly working after downloading the test vectors once a bit of tweaking when the lab files came in and you were on your way.

Now in the "bright new future" we're doing this by hitting the demo server, where any number of things, from connectivity issues, errors in JSON parsing, errors in interpreting JSON parsing, errors in JSON construction for presentation results, and even generating incorrect results can cause client failure. Then of course there's actually errors in algorithm implementation. The point is the only way to test the client is behaving correctly is to hit the server, and then the only way to test the implementation of the algorithms is to hit the server as well. It's a double (at least) whammy as in both cases the server still has to assume that what its talking to is working.

I'm assuming vectors are being generated on a per-request basis, but looking at the tests, a lot of the test vector files could be cached and served, and even re-served, to multiple clients as they do not rely on client generated values. This could be done with no more expense than what is required to copy the file and edit a couple of lines in the headers. Some of these are quite expensive (TDES MTC springs to mind, a lot of verification tests are also in the same boat). This might be worth exploring, it could take a lot of the load off. The cache could have a few potential files for test vector requests/responses/results so some randomness could still be present, and likewise could get rebuilt periodically just to make sure none of us on the outside find ourselves in a rut where we haven't realized. Anyway just a thought.

**Comment by smuellerDD** [comment] 2021-02-08 07:32
Am Sonntag, dem 07.02.2021 um 14:08 -0800 schrieb dghgit:


As a thought: our we have downloaded vectors from each cipher type with a
common set of options for which we created the proper responses that we
checked with the server. That set of vectors will be refreshed occasionally.
But these vectors serve as regression test suite as well as a set of test
vectors we give to customers for trial.

Just a thought....

**Comment by dghgit** [comment] 2021-02-08 08:01
We also do this as well. It's when it's not appropriate that things start to suffer.

**Comment by celic** [comment] 2021-02-08 20:03
Hi, there's a bit to unpack here so I'll start with a bit about our servers.

We have put a lot of work into optimizations across the server. The current state is much better than a year ago, and a year ago, much better than the year before that. During peak times we can receive thousands of vector set requests per hour. With that, work doesn't come into the server consistently through the day. We use the downtime to generate pooled crypto values (Pools) for algorithms where it's appropriate. We even re-use those values whenever applicable with a small toss rate to keep things fresh (10% or less). With the small toss rate, we are seeing the Pools get depleted without enough time to regenerate sufficient values because of how many users and requests are coming into the system. We have had the pools running since Jan 2019 on several long-running crypto tasks like asymmetric key generation and MCTs.  

We have a cluster service set up using an array of physical servers to generate these values for the Pools and on-demand. (dotnet Orleans) All crypto handled by the server is sent through this cluster. In our current state we are limited by the number of physical CPUs we have available on campus. In the future we will be moving to the cloud which will allow for room to grow. This item is waiting on NIST's hosting team to make the final NIST-wide approvals on cloud technology. 

In terms of errors, at the moment we only have one full-time developer on ACVP. @Kritner. The CAVP/CMVP have several platforms upcoming like WebCryptik, and ESV and are looking ahead at other projects. We are in the process of bringing in more resources (this has been ongoing for a while). 

I definitely recommend what @smuellerDD suggested and keeping a collection of vector sets to use locally and refresh them periodically rather than new ones every time. Over time users can build their collections with varying parameter sets.

**Comment by celic** [comment] 2021-02-08 20:30
Would it also make sense for NIST to host "example" vector sets for the algorithms available to download on CSRC like we have in the past for CAVS files?

**Comment by dghgit** [comment] 2021-02-08 23:24
It would probably help - they'd need to be exact replicas so people could validate their parsers and back end implementations, although as  @smuellerDD  touches on the number of permutations are quite large (not a defect obviously, but the kind of advantage that can cause trouble). My suggestion on just caching previous vectors is really an attempt to find a way of dealing with that. In "theory" it mightn't cost much more than serving a web page, but it would eliminate the need to search a web site, potentially missing a matching vector set, or finding out the capabilities you're trying to test don't quite match what's available.

The pooled crypto values was a good idea, I'm pretty sure we'd all be dead in the water already if that hadn't been done.

It would be good if there was some way of getting a clear idea of what is going on (in my original observation I was definitely playing hypotheticals), are there any stats on how many requests come in for which responses are never received? Also how many requests come in asking for samples? Needing samples is probably a sign of nervousness (speaking for myself) - caching those requests with occasional rebuilding might save a lot (assuming the numbers actually stack up) as it may indicate people who are still getting their parsers and backends in order. If it was possible to measure a few things like that it would be a good indicator as to whether it's worth investing more time in trying to optimize things further and where to do it.

**Comment by celic** [comment] 2021-02-08 23:30
As a team, we are implementing some more automated metric tracking. I'll
provide some statistics tomorrow.

**Comment by abkarcher** [comment] 2021-02-09 14:30
Hello,

Just chiming in to echo the sentiment that "example" vector sets, assuming they use the same endpoints, would be a very nice addition to help us test our client (and likely help reduce redundant server load!). 

I often have vector sets saved locally to test against but am frequently adding new algorithms/features we didn't support yet, making adjustments to our netcode, etc. so testing against the server is preferable even if we just get the same values every time. I would make more use of sample sessions if it they were repetitive, equally detailed sets instead of smaller sets (though that is just anecdotal experience). While you obviously wouldn't want to validate anyone based on that, it would, IMO, serve as a much computationally cheaper way for people to check their clients and crypto handlers before formally testing anything.

Andrew

**Comment by celic** [comment] 2021-02-09 16:13
According to our data, about 90% of requests come in against the Demo server rather than Prod. This is fine, but due to the importance of Prod we have more than 10% of our resources dedicated there. Since 1/1, we have 35,606 requests on Demo out of 41,233 total. For Demo this comes out to an average of 1,000 per day. Even with weekends included where there is a small drop-off in usage. 

Demo appears to be hit hardest by a small subset of users. The top 12 users/labs requested 27,430 vector sets from Demo over that time period. 

I don't have data on completion of these requests at the moment. For the server all the work is done up-front whenever possible. If an answer can be generated with the current values in the prompt alone, it is. Normally the verification side can be done with no additional crypto operations or calls to the cluster.

**Comment by dghgit** [comment] 2021-02-10 02:46
It would probably also be useful to have some numbers on what algorithms were the most popular/CPU hogs (especially if answers are being generated up front where they can be). I'd guess SP 800-56A Rev3 is starting to make itself felt, but I know things like the various MCT tests can be very expensive (they certainly chew the CPU at this end).

**Comment by celic** [comment] 2021-02-10 03:24
We are working on collecting that data. It's hard to use a vector set as a
metric when a pbkdf is exponentially more work than an aes-ctr.

**Comment by livebe01** [comment] 2022-06-24 14:51
Hi all, I believe the issues mentioned in this ticket have been addressed. Closing.

**Closed by livebe01** 2022-06-24 14:51 UTC
