### ISSUE TITLE
TDES response submission fails

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#236] opened 2018-03-02 17:04 UTC
While I can successfully upload AES test results and get verdicts, I cannot upload TDES results. Again, I get the following from the server:

< HTTP/1.1 100 Continue
< HTTP/1.1 400 Bad Request
< Server: Apache-Coyote/1.1
< Content-Type: application/json;charset=ISO-8859-1
< Content-Length: 130
< Date: Fri, 02 Mar 2018 17:01:22 GMT
< Connection: close
<

Here is a sample JSON result string for TDES-ECB:
```
[
  {
    "acvVersion":"0.4"
  },
  {
    "vsId":682,
    "testResults":[
      {
        "tcId":1,
        "ct":"88d55e54f54c97b4"
      },
      {
        "tcId":2,
        "ct":"0c0cc00c83ea48fd"
      },
      {
        "tcId":3,
        "ct":"83bc8ef3a6570183"
      },
```

and for MCT

```
      {
        "tcId":246,
        "resultsArray":[
          {
            "key":"6d1f0216f86704cd32948f62f8c46d451c83f72cf1cb0858",
            "pt":"9f9fb22b625e4aeb",
            "ct":"62fbc93ed79e2bf7"
          },
          {
            "key":"0ee5cb292ff82f3bf767158f37e30b10da46e0d59bf10b8c",
            "pt":"62fbc93ed79e2bf7",
            "ct":"32168aa833b45418"
          },
```

**Comment by atvassilev** [comment] 2018-03-05 15:59
@pavelgutin, could you please take a look at this?

**Comment by smuellerDD** [comment] 2018-03-05 16:05
I have more information. The server responds:

```
{
  "acv_version" : "0.4",
  "error" : "Authorization token expired."
}
```

My HTTP header I send to the server is:
POST //acvp/validation/acvp/vectors?vsId=682 HTTP/1.1
Host: demo.acvts.nist.gov
User-Agent: ACVPRetriever/0.0.4
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzMzJhZTM5Ny1kYmJjLTRkY2ItYThhMi03M2EwNTQ5OTU5ODMiLCJpYXQiOjE1MTk5Nzg5MTEsInN1YiI6IkVNQUlMQUREUkVTUz1zbXVlbGxlckBhdHNlYy5jb20sIENOPVN0ZXBoYW4gTXVlbGxlciwgT1U9QUNWUCBEZXZlbG9wbWVudCwgTz1hdHNlYyBpbmZvcm1hdGlvbiBzZWN1cml0eSBjb3JwLCBMPUF1c3RpbiwgU1Q9VGV4YXMsIEM9VVMiLCJpc3MiOiJOSVNUIEFDVlRTIiwidGVzdFNlc3Npb25JZCI6IjU4IiwiZXhwIjoxNTIwMjM4MTExfQ.4FYqwn7eMQvkwt3bLaVHJ3o7oP--m1VV8QJUaVvwnuw
Content-Length: 169769
Expect: 100-continue

**Comment by pavelgutin** [comment] 2018-03-05 20:09
The token is set to expire after 3 days, and the current system doesn't support a way to refresh it. This mechanism will be added in the future. In the meantime, I would suggest just submitting another registration.

**Comment by smuellerDD** [comment] 2018-03-06 06:52
When retrying today, I do not get any responses to help further debugging the problem. I again get retry:30 for hours.

**Comment by pavelgutin** [comment] 2018-03-08 19:32
Can you please provide the JSON  you are submitting, along with the IDs that you are using?

**Comment by atvassilev** [comment] 2018-03-27 18:21
The problems reported here appear caused by other issues, unrelated to the TDES implementation. Many of the server fixes that will be rolled out this week will likely resolve the underlying problems. I am closing this issue for now but if another TDES-specific problems shows up, either reopen it or log a new one.

**Closed by atvassilev** 2018-03-27 18:21 UTC
Labels: bug
