### ISSUE TITLE
SRTP KDF test generation ignores errata for RFC3711

### ISSUE THREAD

**Issue by ldgibbons** [usnistgov/ACVP#1241] opened 2021-09-13 23:22 UTC
The original CAVS test generation for SRTP KDF ignored an existing errata for RFC 3711. As a result, it generated incorrect KDF vectors for sRTCP. Upon realizing the oversight, NIST decided that both the original interpretation and the corrected method of sRTCP KDF would be allowed. One might think that the test vector generation system would implement a switch to decide which mode to use, but this was apparently never done. It now appears that the same problem exists in the ACVP-generated vectors. This needs to be corrected. 

Here is the URL for NIST's decision: 
https://csrc.nist.gov/csrc/media/publications/sp/800-135/rev-1/final/documents/sp800-135r1-informative-note-20160919.pdf

**Comment by livebe01** [comment] 2021-09-16 18:32
Hi @ldgibbons, we're closing this ticket as it's a duplicate of #950. This is something we plan to add, just haven't had an opportunity to get it in as of yet.

**Closed by livebe01** 2021-09-16 18:32 UTC

**Comment by livebe01** [comment] 2023-03-03 18:38
The fix for this is on Demo in release [v1.1.0.28](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.28).
