### ISSUE TITLE
Inconsistency in acvp_protocol section 11.5

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#20] opened 2016-10-13 14:42 UTC
Seems that there is an inconsistency in acvp_protocol section 11.5

---

**11.5. Test Results Request**

The client will send this request to learn the results for an individual vector set.

```
GET /validation/acvp/results?vsId=1 HTTP1.1
User Agent:
Host: www.my-acvpserver.com
Accept: /
HTTP 1.1 200 OK
Status: 200 OK
Content-Type: application/json
Content-Length: <length of results>
{
    "version" : "0.2",
    "results" : {
        "vsId" : 930,
        "disposition" : "incomplete",
        "tests" : [
            { "tcId" : 12340, "result" : "passed" },
            { "tcId" : 12341, "result" : "passed" },
            { "tcId" : 12342, "result" : "incomplete" },
            { "tcId" : 12343, "result" : "passed" }
        ]
    }
} 
```

---

The text prior to the block states it's the client request, which the top of it does appear to be a get request from the client.  However, the JSON included in the block looks to be what the server would respond with, perhaps it was intended to be separated into two blocks to show client request -> server response?

**Comment by atvassilev** [comment] 2016-12-21 22:36
It looks to me that the issue is about the text in Section 11.4 not 11.5. The text in Section 11.4 looks correct, properly delineating the client request and the server response. I am closing this issue.

**Closed by atvassilev** 2016-12-21 22:36 UTC
