### ISSUE TITLE
AES-XTS: incrementing sequence number for the next data unit

### ISSUE THREAD

**Issue by naogot** [usnistgov/ACVP#1444] opened 2023-05-26 07:55 UTC
This is just a confirmation.

I tested AES-XTS with dataUnitLenMatchesPayload "false" and tweakMode "number".
A test case had "sequenceNumber": 1. As it should be converted as little-endian, I set unsigned char i[16] = {0x01, 0x00, 0x00, ... 0x00}; The first data unit was processed successfully.
For the next data unit, I tried 2 as sequenceNumber, that is, i[16] = {0x02, 0x00, 0x00, ... 0x00}; But encrypting this data unit failed (checked using "sample", the encrypted data of the first data unit matched with the expected result, but the second didn't).
When I tried i[16] = {0x01, 0x00, 0x00, ... 0x01}; for the second data unit, the test passed.

The specificatin says that the tweak values are assigned consecutively. The above behavior looks not consecutively incremented (0x1 -> 0x01000000000000000000000000000001), but is it a general implementation?

**Comment by jbrock24** [comment] 2023-05-31 18:44
Hi @naogot Sorry for the lack of a response, I am focusing on this tomorrow as I've been helping get the next release ready, just FYI.

**Comment by livebe01** [comment] 2023-06-14 16:03
Thank you @naogot. This is helpful information. We appreciate the confirmation. I will close this ticket as a duplicate of https://github.com/usnistgov/ACVP-Server/issues/241. We anticipate having a fix for this shortly. Feel free to follow the updates on  https://github.com/usnistgov/ACVP-Server/issues/241 as we address and resolve this.

**Closed by livebe01** 2023-06-14 16:03 UTC
