### ISSUE TITLE
Table columns misaligned in ACVP SHA3 and SHAKE JSON Specification

### ISSUE THREAD

**Issue by kwong-cygnacom** [usnistgov/ACVP#1134] opened 2021-02-23 09:28 UTC
Table 3's columns are misaligned.

**Comment by celic** [comment] 2021-03-15 21:02
This was caused by an error in table 2. This has been fixed, and should be built/deployed shortly. Please close the issue when you can verify.

**Comment by kwong-cygnacom** [comment] 2021-03-16 16:48
I checked a moment ago and did not see the fix. It is still showing "performLargeDataTest" in the algorithm column.

**Comment by celic** [comment] 2021-03-16 16:50
Let me double check the build succeeded.

**Comment by celic** [comment] 2021-03-17 15:54
The build did not run and doesn't say why. I'll get this going.

**Comment by celic** [comment] 2021-03-17 17:40
This is getting built now. Should be up on pages.nist.gov within 15 minutes.

**Closed** 2021-03-17 19:20 UTC
